import os
PATHDIR = os.path.join('emora','_flows', '__***__')
ACTDIR = os.path.join('emora','_activity', '__***__')
CORONADIR = os.path.join('emora','_coronavirus', '__***__')
HOBBYDIR = os.path.join('emora','_hobby', '__***__')
NEWSDIR = os.path.join('emora','_news', '__***__')
OLDLIFEDIR = os.path.join('emora','_old_life', '__***__')
OPENINGDIR = os.path.join('emora','_openings', '__***__')
PETSDIR = os.path.join('emora','_pets', '__***__')
STOPDIR = os.path.join('emora','_stop', '__***__')
TRAVELDIR = os.path.join('emora','_travel', '__***__')
VRDIR = os.path.join('emora','_vr', '__***__')